# Generated by Django 5.2.11 on 2026-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('coreapp', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='ClusterUtilization',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('cluster_ip', models.GenericIPAddressField(unique=True)),
        ('cpu_usage_percent', models.FloatField(blank=True, null=True)),
        ('memory_usage_percent', models.FloatField(blank=True, null=True)),
        ('iops', models.FloatField(blank=True, null=True)),
        ('is_underutilized', models.BooleanField(default=False)),
        ('error_message', models.TextField(blank=True, null=True)),
        ('last_checked', models.DateTimeField(auto_now=True)),
      ],
    ),
    migrations.CreateModel(
      name='TimezoneHealthCheck',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('cluster_ip', models.GenericIPAddressField(unique=True)),
        ('endpoint_type', models.CharField(blank=True, max_length=10)),
        ('status', models.CharField(blank=True, max_length=20)),
        ('details_data', models.JSONField(blank=True, null=True)),
        ('messages_data', models.JSONField(blank=True, null=True)),
        ('last_checked', models.DateTimeField(auto_now=True)),
      ],
    ),
    migrations.CreateModel(
      name='VmCountPerHost',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('cluster_ip', models.GenericIPAddressField(unique=True)),
        ('cluster_name', models.CharField(blank=True, max_length=255)),
        ('status_data', models.JSONField(blank=True, null=True)),
        ('last_checked', models.DateTimeField(auto_now=True)),
      ],
    ),
    migrations.CreateModel(
      name='CZAlert',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('pc_name_or_ip', models.CharField(max_length=255)),
        ('alert_policy_id', models.CharField(max_length=255)),
        ('source_cluster', models.CharField(max_length=255)),
        ('alert_messages', models.JSONField(blank=True, null=True)),
        ('error_message', models.TextField(blank=True, null=True)),
        ('last_checked', models.DateTimeField(auto_now=True)),
      ],
      options={
        'unique_together': {('pc_name_or_ip', 'alert_policy_id', 'source_cluster')},
      },
    ),
  ]
