# Generated by Django 5.2.11 on 2026-07-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('coreapp', '0002_clusterutilization_timezonehealthcheck_and_more'),
  ]

  operations = [
    migrations.AddField(
      model_name='clusterutilization',
      name='status_data',
      field=models.JSONField(blank=True, null=True),
    ),
  ]
