# Generated by Django 5.2.11 on 2026-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_ahvhomeusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coreapp_taskmonitor',
            },
        ),
        migrations.CreateModel(
            name='UnderutilizedCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coreapp_underutilizedcluster',
            },
        ),
        migrations.CreateModel(
            name='VMPowerStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coreapp_vmpowerstates',
            },
        ),
        migrations.DeleteModel(
            name='ClusterUtilization',
        ),
        migrations.DeleteModel(
            name='CZAlert',
        ),
        migrations.DeleteModel(
            name='TimezoneHealthCheck',
        ),
        migrations.DeleteModel(
            name='VmCountPerHost',
        ),
        migrations.RenameField(
            model_name='ahvhomeusage',
            old_name='last_checked',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='prismgatewaystatus',
            old_name='last_checked',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='prismgatewaystatus',
            name='is_online',
        ),
        migrations.AlterField(
            model_name='ahvhomeusage',
            name='cluster_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='ahvhomeusage',
            table='coreapp_ahvhomeusage',
        ),
        migrations.AlterModelTable(
            name='prismgatewaystatus',
            table='coreapp_prismgatewaystatus',
        ),
    ]
