# Generated by Django 5.2.11 on 2026-07-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_ahvhomeusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, unique=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('summary_data', models.JSONField(blank=True, null=True)),
                ('snapshots_data', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
